import Menu from '@/components/Molecules/Menu'
import MMe from '@/components/Molecules/MMe'
import './globals.css'
import { Prompt } from 'next/font/google'

export const prompt = Prompt({
  subsets: ['latin'],
  weight: ['300', '400', '600'],
  variable: '--font-prompt'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={`${prompt.variable} font-prompt`}>
      <head></head>
      <body>
        <Menu />
        <MMe />
        {/* {children} */}
      </body>
    </html>
  )
}
