import Menu from '@/components/Molecules/Menu'
import MMe from '@/components/Molecules/MMe'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Menu />
        <MMe />
        {/* {children} */}
      </body>
    </html>
  )
}
